// Default progress recovered from the 100x100 code map screenshot.
// The bitset is ordered from 0000 to 9999, least-significant bit first.
const FOURLOG_DEFAULT_BITSET =
  "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////fwAAAAgAIP////8AAgAAQEAAAPD///8PAIAAAAAAQAL/////AAAAIAAAAADw////DwAAAAAIAAAC/////wAAAAAAAAIA8P////////////////////8AAAAAAAAAAPD///8PAAAAAAAAAAD/////AgAAAAAAAADw////HwACAAAAAAAA/////wAEAAAQAAAA8P///w8AAAEAABAAAP////8AAABAAAAAAPD///8PAAAAABAAAAD/////AAAABAAABADw////DwAAAAAAAAAB/////wAAAAAAAAAA8P///w8AgAAAAAAAIABEwAABAAAAAQAAAAAAAARgAIEAAAAAAAAAAAAABAgAAQAAAAAAAAAAgAAAAgAMAAAAAAAAABAAAIAAgAAEBACAAAACAAAAIAAAAAAAAABAAAAAAAAIAAAAAAAACEAAAAgAAAIRAAAAAAEAAAAAAAAAAAQAACAAAAAAAAAAAAAAAQAEAAAAAAAAAAAAAmCAAAAAAAAAAAAAAAACMIAAAAAAAAAAAAAAAAIEgAIAAAAAAAAAAEAAAAEAAAAAAAAAAAAIAABAAAAAAAAAAAAAAQAAABAAAAAAAAAAIAAAAAAABCEAAAAAAAQAAAAAAAAACAAAAIAAAAAAAAAAAAACAAAQAAAAAAAAAAAAgAAAAoEAAAAAAAAAAAEwQAAAAAAAAAAAAAAAARhAAAAAAAAABAAAAAABAkAAAAAAAAAAAAAgAIAAAAAAAAAAAAAABCAAIAAAAAAAAAAAgAAAAAAIQQAAAAAAABAAAAAAAAAQAAAAAAACAAAAAAAAAAQAAEBAAAAAAAAAAAAAAQAACAAAAAAAAAAAAEAAAAEAAAAAAAAAAKAAGCAAAAAAAAAAAAAAgAAMIAAAAAAAIAAAAACAAAEgAAAAAAAAAAAAEABAAAAAAAAAACAAAAIAABCBAAAAEAAAAEAAAAAAACAAAAAAAAAIAAAAAAAACAAAAAAAAQAAAAAAAAACAAAAIAAAAAAUAAAAgAAAABQAAAAAAAAIAAAgAIAAAAAAAAAAAABAAAwQAAAAAAAAAAAAAEAABhAAAAAAAAAgAAAAQIBEAAACAAgAAAAAAAgAIAEBAAAIAAAAAAABAAAAQAAAAAAAAAggAAAAAAAQAAAAAAAABAAAAAAAAAQAAAAAgAAAAAAAAAAAAQAAABAAAAAAAQAAAEAAAAACAAAAAAAABAAAEABAAAAAAAAAAAAAIAAGCAAAAAAAAAAAAAAgAAMoAAAAAAAAAAAAACBAARIAAAAAAAAAAAAEAACAAAAAAAAAAACAAAAAACAAAAAAAAAAEAAAAAAACAAAAAAAAAIAAAAAAAACAAAAAEAAQAIAAAAAgAAAAAAIAAAAQAEAAAAgAAAAAQAAAAgAAAIAAAgAIAAAAAAAAAAAABAAAwQAAAAAAAAAAAAAEIA=";

const defaultBytes = Uint8Array.from(
  atob(FOURLOG_DEFAULT_BITSET),
  (character) => character.charCodeAt(0),
);

window.FOURLOG_DEFAULT_GUESSES = Array.from(
  { length: 10000 },
  (_, number) => number,
)
  .filter((number) => defaultBytes[Math.floor(number / 8)] & (1 << (number % 8)))
  .map((number) => String(number).padStart(4, "0"));
